import './styles/global.css'

export const metadata = {
  title: 'Felipe Viana App',
  description: 'Generated by Felipe Viana',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}
