import './styles/global.css'

export const metadata = {
  title: 'Felipe Viana',
  description: 'Generated by Felipe Viana',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-screen">
      <body className=''>{children}</body>
    </html>
  )
}
